server:
  port: 8082

spring:
  application:
    name: blood-donors
  datasource:
    url: jdbc:mysql://localhost:3306/blood_donors_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "******"
    password: "******"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      use_sql_comments: true
